---

- name: "configuration play." 
  hosts: server
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  

  roles:
    - configure-prometheus
    - configure-alertmanager