---

- name: Extract artifact.tar.gz into EC2 server 
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz 
    dest: ~/
    owner: ubuntu
    group: ubuntu
    chmod: 771

# - name: start web server
#   command: npm install; npm run start:prod



...