---

- name: Extract artifact.tar.gz into EC2 server 
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz 
    dest: ~/
    owner: ubuntu
    group: ubuntu

- name: start web server
  command: npm install; npm run start:prod



...