- name: "install alert manager"
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager
    remote_src: yes
    mode: '0777'

- name: "move amtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/amtool
    dest: /usr/local/bin/amtool
    remote_src: yes
    mode: '0777'

- name: "create alertmanager lib directory"
  become: true
  file:
    path: /var/lib/alertmanager
    state: directory

- name: "copy rules.yml to prometheus config folder"
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/

- name: "add alertmanager service configuration."
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/

- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes

- name: "update prometheus.yml file"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: "restart prometheus service"
  become: true
  systemd:
    state: restarted
    name: prometheus
    enabled: yes